### ISSUE TITLE
AMSMaterialsSetting.cpp:1168 calls undefined method get_extruder_id_by_ams_id

### ISSUE THREAD

**Issue by kooscode** [bambulab/BambuStudio#10745]
## Build Error

Compilation fails with:

```
src/slic3r/GUI/AMSMaterialsSetting.cpp:1168: error: 'class Slic3r::MachineObject' has no member named 'get_extruder_id_by_ams_id'
```

## Root Cause

Line 1168 of `AMSMaterialsSetting.cpp` calls a non-existent method directly on `MachineObject`:

```cpp
int ext_id = obj->get_extruder_id_by_ams_id(std::to_string(ams_id));
```

This method was never defined anywhere in the codebase — not on `MachineObject` in `DeviceManager.hpp` or anywhere else.

## Evidence

The same file already uses the correct equivalent elsewhere:

- **Line 597**: `obj->GetFilaSystem()->GetExtruderIdByAmsId(std::to_string(ams_id))`
- **Line 1025**: `obj->GetFilaSystem()->GetExtruderIdByAmsId(std::to_string(ams_id))`

The method `GetExtruderIdByAmsId` is defined on `DevFilaSystem` (`DeviceCore/DevFilaSystem.h:288`, `.cpp:411`) and returns `int`. It correctly looks up the extruder ID from the AMS list, or returns `MAIN_EXTRUDER_ID` / `DEPUTY_EXTRUDER_ID` for virtual trays, or `-1` if not found.

## Fix

Replace line 1168:

```diff
- int ext_id = obj->get_extruder_id_by_ams_id(std::to_string(ams_id));
+ int ext_id = obj->GetFilaSystem()->GetExtruderIdByAmsId(std::to_string(ams_id));
```

It appears a convenience wrapper `get_extruder_id_by_ams_id` was intended for `MachineObject` but the header change was never committed.

**Comment by johanohly** [comment]
Yeah, this seems to have been introduced in #10106

**Comment by XinZhangBambu** [comment]
Thank you for your feedback. the problem has been fixed on https://github.com/bambulab/BambuStudio/commit/22638157e2680dfffcf65062f0caf1152ca40252
